### ISSUE TITLE
Investigate fridges

### ISSUE THREAD

**Issue by torjush** [torjush/Invention-Assignment#2]
- See if there are certain times of day that the fridges are active
- Are there differences between the fridges?
- Are there differences in fridge use depending on the time of day?

**Comment by torjush** [comment]
Accelerometer data seems to give good indications on opening fridge. Clear pattern

**Comment by torjush** [comment]
Investigate windowing further

**Comment by mvanniekerk** [comment]
To get further with windowing, I would suggest investigating splitting the data per "event". Where event is a "continuous" stream of data with low intermediate delays. 

We could extend this by creating a function that takes one event as input and returns a normalized "fingerprint" of this event. Where similar events will have similar fingerprints.
